### ISSUE TITLE
Is the Dataset available?

### ISSUE THREAD

**Issue by AndySAnker** [quantumbeam/xrd-symmetry-prediction#1]
Hi,

Thanks for a great paper and for making the code public!

When I run the code "is_cubic_visualize", I get the following error:
[Errno 2] No such file or directory: 'data/train.csv'

I believe this is because the dataset is not uploaded to Github. Is the dataset public available?

Kind regards
Andy

**Comment by resnant** [comment]
Hi, Andy.

I'm sorry for the very late reply.

Yes, the dataset is available. But we provide it via cloud storage because it is too big to put on GitHub.
The dataset will be automatically downloaded when you run `symmetry_prediction.ipynb`.
https://github.com/quantumbeam/xrd-symmetry-prediction/blob/main/notebooks/symmetry_prediction.ipynb
You can download it manually if needed. Please refer the cell 3 in the notebook. 

I will add a note to the README about how to run the notebooks.

Yuta

**Comment by AndySAnker** [comment]
Dear Yuta,

That make sense, I overlooked that.
Thank you very much!

Kind regards
Andy

Den 1. maj 2021 kl. 19.26 skrev Yuta Suzuki ***@***.******@***.***>>:



Hi, Andy.

I'm sorry for the very late reply.

Yes, the dataset is available. But we provide it via cloud storage because it is too big to put on GitHub.
The dataset will be automatically downloaded when you run symmetry_prediction.ipynb.
https://github.com/quantumbeam/xrd-symmetry-prediction/blob/main/notebooks/symmetry_prediction.ipynb
You can download it manually if needed. Please refer the cell 3 in the notebook.

I will add a note to the README about how to run the notebooks.

Yuta
